release: conductor 0.15.0, relayer 0.13.0
astriaorg/astria pull request #1058
Opened 2024-05-08 21:42 UTC by joroshiba

## Summary
Release breaking change new versions of conductor and relayer which work together.

2024-05-08 21:47 UTC, WafflesVonMaple approved these changes

2024-05-09 10:16 UTC, Fraser999 approved these changes

2024-05-09 14:37 UTC, SuperFluffy requested changes
Blocking this on #1061 being merged

2024-05-09 15:00 UTC, SuperFluffy approved these changes
approving now that #1061 is in the merge queue

2024-05-09 19:06 UTC, merged