bump tendermint-rs to 0.32, penumbra to 0.54.1 and tower-abci to 0.8.0
astriaorg/astria pull request #107
Opened 2023-06-19 18:27 UTC by noot

version bumps, will allow us to use https://github.com/penumbra-zone/penumbra/pull/2723 when/if it's merged so we can remove the patch

2023-06-19 22:41 UTC, SuperFluffy requested changes
Blocking this on the rev vs branch comments so it doesn't get merged accidentally.

2023-06-19 22:41 UTC, SuperFluffy commented on Cargo.toml
> +penumbra-storage = { git = "https://github.com/astriaorg/penumbra.git", branch = "noot/fix-trace" }
Please use fixed `rev`s (or tags) not branches

2023-06-19 22:41 UTC, SuperFluffy commented on Cargo.toml
> +penumbra-tower-trace = { git = "https://github.com/astriaorg/penumbra.git", branch = "noot/fix-trace" }
As above

2023-06-20 16:09 UTC, SuperFluffy approved these changes

2023-06-20 18:25 UTC, steezeburger approved these changes

2023-06-20 18:41 UTC, joroshiba approved these changes

2023-06-20 18:53 UTC, merged