Itamarreif/bridge withdrawer startup
astriaorg/astria pull request #1160
Opened 2024-06-06 17:17 UTC by itamarreif

## Summary
Brief summary of the changes made, ie "what?"

## Background
Brief background on why these changes were made, ie "why?"

## Changes
- List changes which were made.

## Testing
How are these changes tested?

## Metrics
- List out metrics added by PR, delete section if none. 

## Breaking Changelist
- Bulleted list of breaking changes, any notes on migration. Delete section if none.

## Related Issues
Link any issues that are related, prefer full github links.

closes

2024-06-07 20:10 UTC, noot commented on crates/astria-bridge-withdrawer/src/config.rs
> +    // TODO: This should be a u128, but the test fails to parse it as such.
which test?

2024-06-07 20:11 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/ethereum/watcher.rs
> +        let asset_withdrawal_divisor = 10u128.pow(base_chain_asset_precision);
```suggestion
        let asset_withdrawal_divisor = 10u128.pow(18u32.checked_sub(base_chain_asset_precision);
```

2024-06-07 20:12 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/ethereum/watcher.rs
> +        // connect to geth
```suggestion
        // connect to eth node
```

2024-06-07 20:13 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/ethereum/watcher.rs
> +                        "attempt to connect to geth node failed; retrying after backoff",
```suggestion
                        "attempt to connect to rollup node failed; retrying after backoff",
```

2024-06-07 20:13 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/ethereum/watcher.rs
> +        .wrap_err("failed connecting to geth after several retries; giving up")?;
```suggestion
        .wrap_err("failed connecting to rollup node after several retries; giving up")?;
```

2024-06-07 20:14 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/ethereum/watcher.rs
> +            event_to_action(expected_event, denom.id(), denom.clone(), 10u128.pow(18)).unwrap();
```suggestion
            event_to_action(expected_event, denom.id(), denom.clone(), 1).unwrap();
```

after the logic for the divisor above is fixed

2024-06-07 20:18 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/submitter/builder.rs
> +    startup_info_rx: Option<oneshot::Receiver<SequencerStartupInfo>>,
don't think we need an option here - if the oneshot returns an error, then `recv_startup_info` should also error

2024-06-07 20:19 UTC, noot commented on crates/astria-bridge-withdrawer/src/withdrawer/submitter/mod.rs
> +    startup_tx: Option<oneshot::Sender<SequencerStartupInfo>>,
same here, don't think we need option

2024-06-07 20:21 UTC, noot requested changes
please fix `asset_withdrawal_divisor` calculation, otherwise nothing major!

2024-06-08 00:16 UTC, noot approved these changes
lgtm!

2024-06-08 06:45 UTC, SuperFluffy commented
All these startup logics completely ignore shutdown signals.

2024-06-08 18:45 UTC, joroshiba approved these changes
infra approval, lean on janis & elizabeth for rust side.

2024-06-08 18:51 UTC, merged