fix(conductor): update for celestia-node v0.15.0
astriaorg/astria pull request #1367
Opened 2024-08-14 16:44 UTC by ethanoroshiba

## Summary
Updated `fetch_blobs_with_retry()` to accept [Celestia Node v0.15.0](https://github.com/celestiaorg/celestia-node/releases/tag/v0.15.0)'s new `GetAll()` return format. This will still work with Node v0.14.1 as well.

## Background
celestia-node v0.15.0 now returns an empty list of blobs for `GetAll` if blobs are not found, which broke our current `jsonrpsee` error handling in conductor.

## Changes
- Updated `fetch_blobs_with_retry()` to accept the `ParseError` that Json RPC now throws when there are no blobs fetched.

## Testing
E2E tests working

2024-08-14 17:21 UTC, SuperFluffy submitted a review, later dismissed
This checks if parsing failed and is extremely fragile.

Please try this branch instead: https://github.com/eigerco/lumina/pull/340

2024-08-14 17:39 UTC, joroshiba requested changes

2024-08-14 17:39 UTC, joroshiba commented on crates/astria-conductor/src/celestia/fetch.rs
> +                Err(err) if is_null_blobs(&err) => Ok(vec![]),
I think we should keep the old check as well, so that celestia upgrade can happen seamlessly without requiring conductor upgrade in lockstep.

2024-08-15 17:19 UTC, joroshiba approved these changes

2024-08-15 19:21 UTC, merged