feat(cli): feeChange commands
astriaorg/astria pull request #1622
Opened 2024-10-03 15:24 UTC by quasystaty1

## Summary
Adds `FeeChangeAction` to the cli as a sudo command
## Background
The ability to change fees required by different actions is not supported by the cli, should be added as part of adding all sequencer actions as cli commands.

## Changes
- adds `fee-change` sudo Subcommand with all fee change actions

## Testing
There will be a follow-up PR to add CLI test after the ongoing test refactor is completed.
## Related Issues
part of #1474 
closes #1615

2024-10-09 10:15 UTC, sambukowski commented on crates/astria-cli/src/sequencer/sudo/fee_change.rs
> +impl SequenceByteCostMul {
I think it would be better to type out the whole name for this type. `SequenceByteCostMultiplier`

2024-10-09 10:16 UTC, sambukowski commented on crates/astria-cli/src/sequencer/sudo/fee_change.rs
> +struct BridgeLockByteCostMul {
Should use whole name.

2024-10-09 10:22 UTC, sambukowski approved these changes
LGTM. Just nits on struct naming.

2024-10-09 10:33 UTC, joroshiba requested changes
Blocking here on #1647 because it's going to change structure here quite a bit.

2024-10-24 16:29 UTC, ethanoroshiba reviewed
Aside from some typos, LGTM.

2024-10-24 16:29 UTC, ethanoroshiba commented on crates/astria-cli/src/sequencer/sudo/fee_change.rs
> +            SubCommand::IbcRelaeyFee(ibc_relay) => ibc_relay.run().await,
```suggestion
            SubCommand::IbcRelayFee(ibc_relay) => ibc_relay.run().await,
```

2024-10-24 16:29 UTC, ethanoroshiba commented on crates/astria-cli/src/sequencer/sudo/fee_change.rs
> +    /// Chnage Transfer Fee
```suggestion
    /// Change Transfer Fee
```

2024-10-24 16:29 UTC, ethanoroshiba commented on crates/astria-cli/src/sequencer/sudo/fee_change.rs
> +    /// Change Sequence Fee
Would it be better to call this `Rollup Data Submission Fee`? I'm not opinionated either way, but maybe worth considering.

2024-10-24 16:29 UTC, ethanoroshiba commented on crates/astria-cli/src/sequencer/sudo/fee_change.rs
> +    IbcRelaeyFee(IbcRelay),
```suggestion
    IbcRelayFee(IbcRelay),
```

2024-11-05 14:39 UTC, ethanoroshiba approved these changes
LGTM

2024-12-21 00:25 UTC, joroshiba commented
This PR is stale because it has been open 45 days with no activity. Remove stale label or this PR will be
closed in 7 days.

2024-12-29 00:29 UTC, joroshiba commented
This PR was closed because it has been stale.

2024-12-29 00:29 UTC, closed without merging