chore(proto)!: use Transaction, Body, Params for astria tranasctions
astriaorg/astria pull request #1650
Opened 2024-10-09 10:30 UTC by SuperFluffy

## Summary
Brief summary of the changes made, ie "what?"

## Background
Brief background on why these changes were made, ie "why?"

## Changes
- List changes which were made.

## Testing
How are these changes tested?

## Metrics
- List out metrics added by PR, delete section if none. 

## Breaking Changelist
- Bulleted list of breaking changes, any notes on migration. Delete section if none.

## Related Issues
Link any issues that are related, prefer full github links.

closes

2024-10-09 13:14 UTC, joroshiba commented on proto/protocolapis/astria/protocol/transaction/v1alpha1/transaction.proto
> +}
I believe these should still be `TransactionBody` and `TransactionParams`

2024-10-15 14:39 UTC, joroshiba requested changes

2024-10-15 14:57 UTC, SuperFluffy commented on proto/protocolapis/astria/protocol/transactions/v1alpha1/transaction.proto
> +message Params {
I messed up something when rebasing. Fixed now. Sorry for the churn and thank you for noticing!

2024-10-15 15:50 UTC, joroshiba approved these changes

2024-10-16 15:41 UTC, merged