chore(sequencer): add instrumentation
astriaorg/astria pull request #1761
Opened 2024-10-28 21:09 UTC by ethanoroshiba

## Summary
Added instrumentation to most async functions which did not have it.

## Background
Adding instrumentation to all async calls will aid in tracing since spans will be emitted even if no events happen under them.

## Changes
- Added instrumentation to most async functions which did not have it.
- Added `err` argument to the `instrument` macro where applicable.
- Added fields to the `instrument` macro where applicable.

## Testing
Passing all tests.

## Changelogs
No updates required

## Related Issues
closes #1321

2024-12-02 13:07 UTC, Fraser999 requested changes
Blocking this for now (as much a reminder to myself as anything else).

Discussed offline with @ethanoroshiba that this will be revisited to ensure we're only using error-level instrumentation where it's warranted (i.e. where it indicates a serious problem or bug in the logic) and not for non-critical cases (e.g. handling a malformed client request).

2024-12-16 12:37 UTC, Fraser999 commented on crates/astria-sequencer/src/mempool/transactions_container.rs
> +    #[instrument(skip_all, fields(address = %hex::encode(address)))]
I think the address should be base64-encoded.

2024-12-16 12:37 UTC, Fraser999 commented on crates/astria-sequencer/src/mempool/mod.rs
> +    #[instrument(skip_all, fields(address = %hex::encode(address)))]
Address should be base64-encoded I think.

2024-12-16 12:37 UTC, Fraser999 commented on crates/astria-sequencer/src/sequencer.rs
> +            info_span!("Sequencer::run_until_stopped").in_scope(|| {
We could just hold the span in a variable and re-use it throughout this method:
```rust
        let span = info_span!("Sequencer::run_until_stopped");
        let db_exists = config
            .db_filepath
            .try_exists()
            .wrap_err("failed checking for existence of db storage file")?;
        span.in_scope(|| {
            info!(path = %config.db_filepath.display(), "{} storage db", if db_exists {
                "opening"
            } else {
                "creating"
            });
        });
```

2024-12-16 12:37 UTC, Fraser999 commented on crates/astria-sequencer/src/sequencer.rs
> +            .in_scope(|| info!(config.listen_addr, "starting sequencer"));
```suggestion
        span.in_scope(|| info!(config.listen_addr, "starting sequencer"));
```

2024-12-16 12:37 UTC, Fraser999 commented on crates/astria-sequencer/src/sequencer.rs
> +                info_span!("Sequencer::run_until_stopped").in_scope(|| info!("shutting down sequencer"));
```suggestion
                span.in_scope(|| info!("shutting down sequencer"));
```

2024-12-16 12:37 UTC, Fraser999 commented on crates/astria-sequencer/src/sequencer.rs
> +                error_span!("Sequencer::run_until_stopped").in_scope(|| error!("ABCI server task exited, this shouldn't happen"));
```suggestion
                span.in_scope(|| error!("ABCI server task exited, this shouldn't happen"));
```

2024-12-18 18:47 UTC, ethanoroshiba commented on crates/astria-sequencer/src/sequencer.rs
> +                error_span!("Sequencer::run_until_stopped").in_scope(|| error!("ABCI server task exited, this shouldn't happen"));
Made requested changes in 66e1b84 :)

2024-12-19 11:38 UTC, Fraser999 approved these changes

2024-12-19 15:13 UTC, merged