Eng 824/auctioneer
astriaorg/astria pull request #1839
Opened 2024-11-29 11:09 UTC by SuperFluffy

## Summary
Brief summary of the changes made, ie "what?"

## Background
Brief background on why these changes were made, ie "why?"

## Changes
- List changes which were made.

## Testing
How are these changes tested?

## Changelogs
Ensure all relevant changelog files are updated as necessary. See
[keepachangelog](https://keepachangelog.com/en/1.1.0/#how) for change
categories. Replace this text with e.g. "Changelogs updated." or "No updates
required." to acknowledge changelogs have been considered.

## Metrics
- List out metrics added by PR, delete section if none. 

## Breaking Changelist
- Bulleted list of breaking changes, any notes on migration. Delete section if none.

## Related Issues
Link any issues that are related, prefer full GitHub links.

closes

2025-01-14 16:34 UTC, SuperFluffy commented
I want to get https://github.com/astriaorg/astria/pull/1913 in (tiny PR but feels wrong to have it in here).

2025-01-17 12:51 UTC, SuperFluffy commented on crates/astria-core/CHANGELOG.md
> +- Add module `astria_sequencer::sequencerblock::optimistic::v1alpha1`
Addressed in c5d6f9c98dd21b6703c988aaae44fb27a41713cd

2025-01-17 12:52 UTC, SuperFluffy commented on crates/astria-sequencer/src/app/event_bus.rs
> +    pub(crate) fn process_proposal_blocks(&mut self) -> EventReceiver<Arc<SequencerBlock>> {
Indeed; removed c5d6f9c98dd21b6703c988aaae44fb27a41713cd

2025-01-17 12:52 UTC, SuperFluffy commented on crates/astria-sequencer/src/app/event_bus.rs
> +    pub(crate) fn subscribe(&self) -> EventBusSubscription {
Done in c5d6f9c98dd21b6703c988aaae44fb27a41713cd

2025-01-17 13:12 UTC, SuperFluffy commented on crates/astria-sequencer/src/app/event_bus.rs
> +    is_init: CancellationToken,
thank you very much for the thorough review and pointing this out. We went through several iterations for this type and failed to realize the behavior of subscribe. Addressed in 49d3be4f

2025-01-17 13:12 UTC, SuperFluffy commented on crates/astria-sequencer/src/app/event_bus.rs
> +            "events must be set after is_init is triggered; this means an invariant was violated",
Adjusted the expect message with a lengthy explanation  49d3be4f

2025-01-17 13:20 UTC, SuperFluffy commented on crates/astria-sequencer/src/grpc/mod.rs
> +        list
I was about to grudgingly use `Itertools::join` (because allocation...), when I noticed https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.format, which eluded me so far. This reads much nicer now and has no allocation! 40ad4ca5

2025-01-17 14:50 UTC, Fraser999 commented on crates/astria-sequencer/src/app/event_bus.rs
> +        self.process_proposal_blocks.clone()
Looks like removing `mark_latest_event_as_seen` was missed?

2025-01-17 14:56 UTC, Fraser999 approved these changes
Optimistic approval of the sequencer and core code, pending addressing one minor comment.

2025-01-26 17:16 UTC, SuperFluffy commented on charts/sequencer/Chart.yaml
> +appVersion: "1.0.1"
Is this correct? Or should this be in lockstep with the underlying app (in this case sequencer, which as of this patch will still be at `1.0.0`?)

2025-01-26 17:17 UTC, SuperFluffy commented
Open question for @astriaorg/infra reviewers:

should auctioneer, sequencer, get be bundled in a separate chart (compare `evm-rollup` and `evm-stack`)?

2025-01-27 11:13 UTC, quasystaty1 requested changes
Overall chart looks ok. Few syntax requested changes.

Also, does the auctioneer should run by default in the dev cluster? If so, the sequencer dev value should reflect it. This leads to the question of which repo should you for the evm instance `astria-geth` or `flame`.

2025-01-28 16:48 UTC, SuperFluffy commented
This is currently blocked on https://github.com/astriaorg/flame/pull/30. It needs to be:

1. reviewed and merged
2. released.

Thereafter the charts in this PR can be updated.

2025-02-11 10:18 UTC, SuperFluffy commented
Commits [6108aab](https://github.com/astriaorg/astria/pull/1839/commits/6108aab91962fd14a17a760ecf9c503f9ead07e6) and [ef5e850](https://github.com/astriaorg/astria/pull/1839/commits/ef5e8506475732b778de5237e08b8ebcffd59071) contain two changes:

1. the nomenclature `optimistic` was changed to `proposed` when talking about blocks received from sequencer (this primarily affects telemetry and the `astria_auctioneer_proposed_blocks_received` metric (formerly `*optimistic_blocks_received`).
2. removed metric counter `astria_auctioneer_auctions_submitted` (this is covered by the histogram reporting the submission latency for successfully submitted auctions)

2025-02-11 10:40 UTC, quasystaty1 approved these changes
infra approval. Note, a test is failing duo to chart dependency issue. run:
`helm dependency update ./charts/evm-stack` to resolve.

2025-02-11 20:15 UTC, aajimal approved these changes

2025-02-12 16:02 UTC, joroshiba approved these changes
approved for API and infra w/ minor nits on proto naming stuff

2025-02-13 12:58 UTC, SuperFluffy commented on proto/executionapis/astria/auction/v1alpha1/bid.proto
> +  bytes rollup_parent_block_hash = 4;
Done in [e52c1b9](https://github.com/astriaorg/astria/pull/1839/commits/e52c1b93823d9c701252da62d471b8007ae09605)

2025-02-13 12:58 UTC, SuperFluffy commented on proto/executionapis/astria/auction/v1alpha1/bid.proto
> +message GetBidStreamRequest {}
Done in [e52c1b9](https://github.com/astriaorg/astria/pull/1839/commits/e52c1b93823d9c701252da62d471b8007ae09605) but then superseded by [000b66c](https://github.com/astriaorg/astria/pull/1839/commits/000b66c40e9f311ad99839d0dd2b39fc0e095ae3)

2025-02-14 12:05 UTC, merged