chore: remove isTerminal dependency and use std::io::isTerminal
astriaorg/astria pull request #203
Opened 2023-07-29 14:38 UTC by jim4067

resolves #170 

- add a `rust-toolchain` for MSRV.
- remove imports of `isTerminal` and replace with `std::io::isTerminal`.
- remove isTermnal in the `Cargo.toml` files.

2023-07-29 14:41 UTC, dereksione approved these changes

2023-07-31 11:32 UTC, SuperFluffy requested changes
Thank you for your contribution!

A lot of CI tests are currently failing because while this PR demands rust version of 1.70 stable some jobs either require nightly (running rustfmt) or have a pinned rust version of 1.69 (the docker builds).

Can you please also update the docker file and (instead of pinning the toolchain), add a `rust-version` entry to the `[package]` section of the affected binary crates?

2023-07-31 11:32 UTC, SuperFluffy commented on rust-toolchain
This is problematic with the way our gh actions are currently set up. Please remove.

2023-07-31 17:00 UTC, jim4067 commented
I think for the rust workflow clippy and rustfmt components could be added.

Thanks for explaining why docker is also failing.
If explicitly specifying the rust version fixes this, where can I make the necessary changes?

2023-08-01 12:45 UTC, SuperFluffy commented
> I think for the rust workflow clippy and rustfmt components could be added.
> 
> Thanks for explaining why docker is also failing. If explicitly specifying the rust version fixes this, where can I make the necessary changes?

You need to update `.github/workflows/rust.yml` and `containerfiles/Dockerfile`.

2023-08-16 13:47 UTC, SuperFluffy commented
superseded by #271

2023-08-16 13:47 UTC, closed without merging