doc: sequencer relayer information on interfaces
astriaorg/astria pull request #296
Opened 2023-08-22 21:56 UTC by joroshiba

## Summary

Adding docs on the interfaces which sequencer relayer interacts with. 

## Background

Most of the information on this either requires reading code, having read the code previously, or searching slack history right now.

## Changes

- Add a doc for sequencer relayer.

## Related Issues

Link any issues that are related, prefer full github links.

closes

2023-08-23 20:21 UTC, steezeburger requested changes

2023-08-23 20:26 UTC, noot commented on specs/relayer.md
> +listens on, and writes batches sets of blocks to DA.
```suggestion
The Astria Sequencer Relayer (referred to as relayer from here on out) reads
new blocks from the sequencer, publishes them to the gossipnet which Conductor
listens on, and writes batches sets of blocks to DA.
```

2023-08-23 20:26 UTC, noot commented on specs/relayer.md
> +relays/writes data from its proposer.
```suggestion
It is run as a sidecar to a sequencer validator node, and each instance only
relays/writes data from blocks it proposes.
```

2023-08-23 20:28 UTC, noot commented on specs/relayer.md
> +proposer, it is converted into the `SequencerBlockData` shape
```suggestion
validator key, it is converted into the `SequencerBlockData` structure
```

2023-08-23 20:30 UTC, noot commented on specs/relayer.md
> +have transactions in the Astria block. All of these are serialized to JSON and
> JSON

this will be changed to proto soon

2023-08-23 20:32 UTC, noot commented on specs/relayer.md
> +The Astria Sequencer Relayer (referred to as relayer from here on out), reads
maybe add a quick line explicitly explaining why we need the relayer; ie "data sequenced by the sequencer chain needs to be written to a data availability layer; this has been separated from the core sequencer node functionality into its own relayer program" or something like that

2023-08-23 20:33 UTC, noot reviewed
should this also explain a bit about writing to DA (ie. the relayer needs a celestia node with an unlocked celestia wallet?)

2023-08-24 18:15 UTC, steezeburger requested changes

2023-09-01 22:14 UTC, noot approved these changes
looks nice! a few minor comments, good to have this in.

2023-09-01 22:14 UTC, noot commented on specs/sequencer-relayer.md
> +The Astria Sequencer Relayer (Relayer), is a stateless service which reads new
```suggestion
The Astria Sequencer Relayer (Relayer) is a stateless service which reads new
```

2023-09-01 22:14 UTC, noot commented on specs/sequencer-relayer.md
> +until it is included, once it has been included the next set of queued
```suggestion
until it is included. Once it has been included, the next set of queued
```

2023-09-01 22:14 UTC, noot commented on specs/sequencer-relayer.md
> +faster than Celestia block times, we create a queue of yet to be written blocks.
maybe explicitly say "we make 1 batch write of data per celestia block, which consists of many sequencer blocks"?

2023-10-10 16:28 UTC, sambukowski commented on specs/sequencer-relayer.md
> +        - integer number of subscribed gossipnet members
Should this be replaced with the Conductor websocket status?

2023-10-10 16:32 UTC, sambukowski commented on specs/sequencer-relayer.md
> +### P2P/Gossipnet
can remove

2023-10-10 16:36 UTC, sambukowski commented on specs/sequencer-relayer.md
> +`SignedNamespacedData` (link), which will is parsed into bytes for inclusion in
missing link

2023-10-10 16:42 UTC, sambukowski commented
Overall, looks good!
The sections referring to gossip need to be removed/updated.

2023-10-27 21:45 UTC, joroshiba commented
Severely out of date

2023-10-27 21:45 UTC, closed without merging