Remove gossipnet from relayer
astriaorg/astria pull request #366
Opened 2023-09-14 10:13 UTC by emhane

## Summary
remove gossipnet from relayer

## Background
relayer has in the past submitted blocks to gossipnet for conductor to receive them earlier than celestia. conductor will receive blocks via RPC instead of p2p here forth from some sequencer node(s).

## Changes
- remove gossip net from relayer

## Testing
removing mock conductor from relayer integration tests, this should not alter the way celestia interacts with tests

## Breaking Changelist
- relayer integration test `slow_celestia_leads_to_bundled_blobs` stops working though removing code that submits a block from gossip net doesn't effect the way a block is submitted to celestia. I am positive it has to do with the test framework, specifically how it interleaves time, which is out of scope of this pr to fix.

## Related Issues
#332

closes

2023-09-14 11:39 UTC, SuperFluffy commented
I fixed the issue testing the batched celestia blobs.

You are right that it has to do with how time is handled in tokio tests: it auto-advances to the next tick, but that happens faster than the mock response + jsonrpc + deserialization, causing all sorts of issues.

2023-09-17 09:56 UTC, noot commented on crates/astria-sequencer-relayer/src/relayer.rs
> +        println!("submission res {:?}", submission_result);
remove

2023-09-17 10:53 UTC, SuperFluffy commented
@emhane If you give permission I will push my patches fixing the blackbox tests to this branch so that CI passes (Monday or Tuesday).

2023-09-18 02:00 UTC, emhane commented
> I fixed the issue testing the batched celestia blobs.
> 
> You are right that it has to do with how time is handled in tokio tests: it auto-advances to the next tick, but that happens faster than the mock response + jsonrpc + deserialization, causing all sorts of issues.

if you advance time by the tick interval, naturally this happens. not quite sure how you mean the issue is how tokio handles time in tests? the time is controlled manually in these tests.

if you push the patch to a branch I can check it out.

2023-09-18 15:49 UTC, SuperFluffy commented
@emhane see PR #384 which fixes the tests

2023-09-18 15:54 UTC, SuperFluffy requested changes
The config must be changed to reflect that writing to celestia is now the only functionality of sequencer-relayer.

Please fix the failing tests before merge. They are fixed in #384

2023-09-18 16:39 UTC, emhane commented
> @emhane see PR #384 which fixes the tests

your open pr implements the same issue. I implemented it because it was assigned to, shame with duplicate work, so would have preferred if you would have just assigned yourself.

2023-09-18 16:39 UTC, closed without merging

2023-09-18 16:44 UTC, SuperFluffy commented
@emhane 
> > @emhane see PR #384 which fixes the tests
> 
> your open pr implements the same issue. I implemented it because it was assigned to me, shame with duplicate work, so would have preferred if you would have just assigned yourself.
I needed to investigate why the tests were failing to merge this PR, which is the brunt of #384, and because you noted this:

 >  I am positive it has to do with the test framework, specifically how it interleaves time, which is out of scope of this pr to fix.