Conductor: fix config loading from environment to have more control
astriaorg/astria pull request #387
Opened 2023-09-18 21:56 UTC by steezeburger

## Summary
This PR refactors how we load values from the environment so that we have more control on which envars are used.

## Background
A user's locally loaded environment should not affect test outcomes.

## Changes
- added `prefix` argument to `from_environment` and `populate_environment_from_example`

## Testing
- I fixed the test that was erroneously failing previously.

## Breaking Changelist
- You must now pass in a prefix or `None` to `from_environment`

closes https://github.com/astriaorg/astria/issues/386

2023-09-18 22:02 UTC, sambukowski approved these changes

2023-09-19 09:48 UTC, noot commented on crates/astria-conductor/src/config.rs
> +    fn from_environment(prefix: Option<&str>) -> Result<Config, figment::Error> {
it appears `None` is the only value passed in here (excluding tests), maybe just remove the param and the `Some` case?

2023-09-19 09:53 UTC, SuperFluffy requested changes
IMO the code can be simplified by not using the option but instead changing `Config::from_environment` to take a `&str`, and then defining a hardcoded string to use in `fn get`.

Also, I think it would be great if we expanded this to the other crates.

2023-09-19 16:17 UTC, joroshiba approved these changes
Generally LGTM, although I agree with comments that we should set a const and always take a string instead of using `None` value.

Assuming that is taken care of, approved.

2023-09-19 17:12 UTC, steezeburger commented
> IMO the code can be simplified by not using the option but instead changing `Config::from_environment` to take a `&str`, and then defining a hardcoded string to use in `fn get`.
> 
> Also, I think it would be great if we expanded this to the other crates.

Totally! I made an issue for pulling this out into its own crate https://github.com/astriaorg/astria/issues/398

2023-09-19 19:05 UTC, SuperFluffy approved these changes
Looking good, ty for the changes

2023-09-19 19:21 UTC, merged