Necessary Astria package Dockerfile updates after moving to monorepo
astriaorg/astria pull request #47
Opened 2023-06-05 20:34 UTC by steezeburger

* rename astria packages to match new crate structure
* add buf build dependency now that astria relayer uses astria-protos

2023-06-07 17:09 UTC, joroshiba approved these changes

2023-06-08 12:58 UTC, noot approved these changes

2023-06-08 16:38 UTC, SuperFluffy requested changes
This *might* not be a problem, but it's best to ensure that the debian releases match.

Also, since both of these dockerfiles are basically carbon copies of each other we could merge them, provide a `ARG TARGET_BINARY` (or whatever), and call the image build executable with `TARGET_BINARY=astria-sequencer-relayer` or `TARGET_BINARY=astria-conductor`, respectively.

2023-06-08 21:23 UTC, steezeburger commented on crates/astria-conductor/Dockerfile
>  FROM gcr.io/distroless/cc:debug
Cool I created a task to capture this
https://github.com/astriaorg/astria/issues/61

2023-06-09 13:16 UTC, SuperFluffy approved these changes
Looks good to with the change. Doing the single-file-docker in #61 makes sense to me.

2023-06-09 15:04 UTC, merged