renamed prev_state_root in DoBlockRequest to prev_block_hash
astriaorg/astria pull request #55
Opened 2023-06-07 16:48 UTC by akansjain

In crates/astria-proto/proto/astria/execution/v1/execution.proto, there is a the gRPC method DoBlockRequest has a field called prev_state_root but what's actually passed here is the parent block hash, and should be called prev_block_hash.

Therefore, field prev_state_root is renamed to prev_block_hash in DoBlockRequest.

2023-06-07 16:49 UTC, akansjain commented
Hey @noot ,
Please review my PR.

2023-06-07 17:09 UTC, joroshiba commented
Thanks for the contribution, can you also update `astria-conductor` to use the new grpc as well [here](https://github.com/astriaorg/astria/blob/main/crates/astria-conductor/src/execution_client.rs#LL68C13-L68C28)

2023-06-07 18:59 UTC, joroshiba commented on crates/astria-conductor/src/execution_client.rs
> +            // Updated field name: prev_block_hash
We can just remove this comment.

2023-06-07 19:04 UTC, joroshiba commented on crates/astria-conductor/src/execution_client.rs
> +            prev_block_hash: prev_block_hash.clone(),
I don't think the clone is necessary here, would prefer the shorthand.

2023-06-07 19:46 UTC, noot commented on crates/astria-conductor/src/execution_client.rs
> +            prev_block_hash: prev_block_hash.clone(),
```suggestion
            prev_block_hash,
```

2023-06-12 18:53 UTC, joroshiba requested changes

2023-06-12 18:53 UTC, joroshiba commented on crates/astria-conductor/src/execution_client.rs
> +            // Updated field name: prev_block_hash
```suggestion
```

2023-07-04 22:06 UTC, noot commented
closing due to staleness

2023-07-04 22:06 UTC, closed without merging