chore(core): Update docs to reference astria-core instead of astria-proto
astriaorg/astria pull request #777
Opened 2024-03-04 12:34 UTC by bharath-123

## Summary
astria-proto repo was renamed to astria-core in https://github.com/astriaorg/astria/pull/644 . This PR addresses the corresponding README changes to change `astria-proto` to `astria-core`

## Background
The [https://github.com/astriaorg/astria/tools/protobuf-compiler/README.md](https://github.com/astriaorg/astria/tools/protobuf-compiler/README.md) includes the path which points to where the generated code for the protobufs resides. It points to a stale `astria-proto` link which can be confusing to new developers looking at the codebase. The other README changes come as a result of this observation. 

## Changes
- Updates to READMEs

## Testing
No need of testing

## Metrics
No need of metrics

## Breaking Changelist
No breaking changes

## Related Issues
Link any issues that are related, prefer full github links.

closes

2024-03-04 22:17 UTC, joroshiba requested changes

2024-03-05 09:17 UTC, bharath-123 commented on README.md
> +* [core](https://github.com/astriaorg/astria/tree/main/crates/astria-core):
I have pointed it to the `src/generated` within the astria-core repo. Does that work?

2024-03-05 09:38 UTC, SuperFluffy reviewed
Happy to approve this after the link to `proto` is amended.

2024-03-05 09:38 UTC, SuperFluffy commented on README.md
> +* [core](https://github.com/astriaorg/astria/tree/main/crates/astria-core/src/generated):
Agree with @joroshiba: this should point to the proto spec, not to a library crate (`core`), nor directly to the generated code.

There are essentially 5 components here: `conductor`, `composer`, `sequencer`, `sequencer-relayer`, and the protobuf spec.

2024-03-06 12:04 UTC, SuperFluffy approved these changes
Tentatively approving the PR. Please address the last two points and feel free to merge.

2024-03-06 12:04 UTC, SuperFluffy commented on README.md
> +Note that the `astria-core` generates its code by running tests (and verifying
This part of the README is outdated and can be removed. `astria-core` no longer does this.

2024-03-06 12:04 UTC, SuperFluffy commented on README.md
>    relevant protobufs for Astria types.
this should read something like `the protobuf spec to interact with Astria services`

2024-03-07 06:50 UTC, merged